language: python
python:
  - 2.7

install:
  - mkdir -p buildout-cache/{eggs,downloads}
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bin/test

notifications:
  irc:
    - "irc.homelien.no#yaphan"
